version: '3'
services:
  web:
    build: ./flaskapp
    container_name: web
    ports:
      - '5000:5000'
    volumes:
      - ./flaskapp:/app
    links:
      - mongodb
  mongodb:
    image: mongo:3.6
    container_name: mongodb


